BlogMundoDesignMVC/Models/Contato.cs
namespace BlogMundoDesignMVC.Models
{
    public class Contato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Mensagem { get; set; }
    }
}

BlogMundoDesignMVC/Models/Profissional.cs
namespace BlogMundoDesignMVC.Models
{
    public class Profissional
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public int Idade { get; set; }
        public int Sexo { get; set; }

        public string Email { get; set; }

        public string Telefone { get; set; }

        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }

        public bool PossuiExperiencia { get; set; }

        //public string TipoExperiencia { get; set; }

        public bool ExperienciaGarcom { get; set; }
        public bool ExperienciaBarman { get; set; }
        public bool ExperienciaSeguranca { get; set; }
        public bool ExperienciaDj { get; set; }
        public bool ExperienciaCopeiro { get; set; }
        public bool ExperienciaFritadeira { get; set; }
        public bool ExperienciaHostness { get; set; }
        public bool ExperienciaMusico { get; set; }
        public bool ExperienciaCaixa { get; set; }
        public bool ExperienciaPromotorEventos { get; set; }
        public bool ExperienciaAnimadorFestas { get; set; }
        public bool ExperienciaManobrista { get; set; }
        public bool ExperienciaSevicosGerais { get; set; }
        public bool ExperienciaFotografo { get; set; }

        public string LocalExperiencia { get; set; }

        public bool EfetuouPagamento { get; set; }
		public bool FreeMode { get; set; }


    }
}

BlogMundoDesignMVC/Controllers/ContatoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogMundoDesignMVC.Contexto;
using BlogMundoDesignMVC.Models;

namespace BlogMundoDesignMVC.Controllers
{
    public class ContatoesController : Controller
    {
        private Contexto.Contexto db = new Contexto.Contexto();

        // GET: Contatoes
        public ActionResult Index()
        {
            return View(db.Contatos.ToList());
        }

        // GET: Contatoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contatos.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // GET: Contatoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contatoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Email,Telefone,Mensagem")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Contatos.Add(contato);
                db.SaveChanges();
                return RedirectToAction("About", "Postagem");
            }

            return View(contato);
        }

        // GET: Contatoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contatos.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // POST: Contatoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Email,Telefone,Mensagem")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contato);
        }

        // GET: Contatoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contatos.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // POST: Contatoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contato contato = db.Contatos.Find(id);
            db.Contatos.Remove(contato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogMundoDesignMVC/Controllers/PostagemController.cs
using BlogMundoDesignMVC.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace BlogMundoDesignMVC.Controllers
{
    public class PostagemController : Controller
    {
       

        // GET: Postagem
        public ActionResult Index()
        {
            var wc = new WebClient();
            var json = wc.DownloadString("https://blogmundodesign.firebaseio.com/postagens.json");
            var lista = JsonConvert.DeserializeObject<IDictionary<string, Postagem>>(json);

            ViewBag.ListaPostagem = lista;

            return View();
        }

        // GET: Postagem/Details/5
        public ActionResult Details(string idPostagem)
        {

            var wc = new WebClient();
            var json = wc.DownloadString("https://blogmundodesign.firebaseio.com/postagens.json");
            var lista = JsonConvert.DeserializeObject<IDictionary<string, Postagem>>(json);

            var postagem = new Postagem();

            foreach (var item in lista)
            {
                if (item.Key == idPostagem)
                {


                    postagem.ConteudoPrimeiroNivelPostagem = item.Value.ConteudoPrimeiroNivelPostagem;
                    postagem.ConteudoSegundoNivelPostagem = item.Value.ConteudoSegundoNivelPostagem;
                    postagem.DataPostagem = item.Value.DataPostagem;
                    postagem.NomeAutor = item.Value.NomeAutor;
                    postagem.SubtituloPostagem = item.Value.SubtituloPostagem;
                    postagem.TituloMeioPostagem = item.Value.TituloMeioPostagem;
                    postagem.TituloPostagem = item.Value.TituloPostagem;
                    postagem.ImagemPostBase64 = item.Value.ImagemPostBase64;
                    postagem.FotoAutor = item.Value.FotoAutor;

                }
            }


            return View(postagem);
        }

        public ActionResult NovaPostagem()
        {
            return View();
        }

        // GET: Postagem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Postagem/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Postagem/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Postagem/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Postagem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Postagem/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

BlogMundoDesignMVC/Controllers/ProfissionalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogMundoDesignMVC.Contexto;
using BlogMundoDesignMVC.Models;

namespace BlogMundoDesignMVC.Controllers
{
    public class ProfissionalsController : Controller
    {
        private Contexto.Contexto db = new Contexto.Contexto();

        // GET: Profissionals
        public ActionResult Index()
        {
            return View(db.Profissionais.ToList());
        }

        // GET: Profissionals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profissional profissional = db.Profissionais.Find(id);
            if (profissional == null)
            {
                return HttpNotFound();
            }
            return View(profissional);
        }

        // GET: Profissionals/CreateFree
        public ActionResult CreateFree()
        {
            return View();
        }

        // POST: Profissionals/CreateFree
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFree(Profissional profissional)
        {
            if (ModelState.IsValid)
            {
                db.Profissionais.Add(profissional);
                db.SaveChanges();
                return RedirectToAction("FinalizarFree", "Profissionals");
            }

            return View(profissional);
        }
		
        // GET: Profissionals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profissionals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Profissional profissional)
        {
            if (ModelState.IsValid)
            {
                db.Profissionais.Add(profissional);
                db.SaveChanges();
                return RedirectToAction("Finalizar", "Profissionals");
            }

            return View(profissional);
        }

        

        // GET: Profissionals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profissional profissional = db.Profissionais.Find(id);
            if (profissional == null)
            {
                return HttpNotFound();
            }
            return View(profissional);
        }

        // POST: Profissionals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Sobrenome,Idade,Sexo,Logradouro,Bairro,Cidade,Estado,PossuiExperiencia,TipoExperiencia,LocalExperiencia,EfetuouPagamento")] Profissional profissional)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profissional).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profissional);
        }

        // GET: Profissionals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profissional profissional = db.Profissionais.Find(id);
            if (profissional == null)
            {
                return HttpNotFound();
            }
            return View(profissional);
        }

        // POST: Profissionals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profissional profissional = db.Profissionais.Find(id);
            db.Profissionais.Remove(profissional);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Contato()
        {
            return View();
        }

        public ActionResult Finalizar()
        {
            return View();
        }
    }
}

BlogMundoDesignMVC/Views/Profissionals/Contato.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Fale Conosco</title>
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/css/main.css" rel="stylesheet" />
</head>
<body>
    <main class="container left-container">
        <div class="row">
            <div id="menu-target">
                <ul>
                    <li><i class="fa fa-home"></i><a href="@Url.Action("About", "Postagem")">Home</a></li>
                    <li><i class="fa fa-anchor"></i><a href="@Url.Action("Create", "Profissionals")">Faça Parte</a></li>
                    <li><i class="fa fa-paper-plane"></i><a href="@Url.Action("Contato", "Profissionals")">Fale Conosco</a></li>
                </ul>
                <hr>

            </div>
            <section class="sidebar col-md-4 col-sm-12" style="background-image:url(/Content/img/home_default.jpg)">
                <span class="menu-trigger animated fadeInDown">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </span>

                <!--<div class="site-info">
                    <div class="primary-info">
                        <h1>Vou de Freela</h1>
                        <p>Aqui uma mensagem bonitinha</p>
                        <p>Aqui outra mensagem bonitinha</p>
                    </div>
                    <div class="secondary-info">
                        <p>
                            <a class="btn btn-primary" href="@Url.Action("Create", "Profissionals")"><i class="fa fa-user-plus"></i>Faça parte!</a>
                        </p>
                    </div>
                </div>-->
            </section><!-- end sidebar -->

        </div>
        <section class="col-md-8 col-sm-6 col-md-offset-6 main-content">
            <div class="sub-nav">

                <h3>Fale Conosco</h3>
                @using (Html.BeginForm("Create", "Contatoes"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label for="Nome">Nome</label>
                        <input type="text" placeholder="Guilherme Junqueira" class="form-control" name="Nome" id="Nome">
                    </div>
                    @*<div class="form-group">
                            <label for="company">Empresa</label>
                            <input type="text" placeholder="Exemplo Ltda" class="form-control" name="company">
                        </div>*@
                    <div class="form-group">
                        <label for="Email">E-mail</label>
                        <input type="text" placeholder="examplo@email.com" class="form-control" name="Email" id="Email">
                    </div>
                    <div class="form-group">
                        <label for="Telefone">Telefone</label>
                        <input type="tel" placeholder="+55 31 998217779" class="form-control" name="Telefone" id="Telefone">
                    </div>

                    <div class="form-group">
                        <label for="Mensagem">Mensagem</label>
                        <textarea class="form-control" name="Mensagem" id="Mensagem" placeholder="Olá, meu nome..."></textarea>
                    </div>

                    <div class="form-group">
                        <input class="btn btn-laranja" type="submit" value="Enviar">
                    </div>
                }
            </div>
        </section>
    </main>


    @Scripts.Render("~/bundles/jquery")
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="~/Content/js/vendor/jquery.jpanelmenu.min.js"></script>
    <script src="~/Content/js/vendor/bootstrap.min.js"></script>
    <script src="~/Content/js/vendor/fastclick.min.js"></script>
    <script src="~/Content/js/main.js"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-96040922-1', 'auto');
        ga('send', 'pageview');

    </script>


</body>
</html>

BlogMundoDesignMVC/Views/Profissionals/Create.cshtml
@model BlogMundoDesignMVC.Models.Profissional

@{
    ViewBag.Title = "Cadastro";
}


<section class="col-md-8 col-sm-6 col-md-offset-6 main-content">
    <h3>Como funciona nossa plataforma.</h3>

    <p>Para ganhar visibilidade junto aos nossos parceiros promotores de eventos primeiro você deve preencher o formulário de cadastro. Ele é simples e auto explicativo, mas se surgirem dúvidas você pode nos enviar um e-mail.</p>

    <p>O próximo passo é pagar a taxa de cadastro. Os 100 primeiros cadastrados no Vou de Freelas vão ganhar uma força nossa e terão apenas que pagar <strong>uma taxa única de cadastro de 7,90</strong> que será válida por 6 meses. Após este período você poderá escolher renovar seu cadastro e aderir ou não à proposta de pagamento vigente; não há obrigatoriedade de permanência.</p>
    <p>Após a confirmação de pagamento, seu cadastro já será enviado para nossos parceiros que terão total disponibilidade para fazer contato contigo.</p>
    <p>Por fim, basta fechar o negócio, fazer um bom trabalho e aguardar novas propostas.</p>
    <p>Simples não é!? A idéia é justamente essa, simplificar para que você faça dinheiro o mais rápido possível!</p>

    <h3>Faça parte</h3>

    <p>Aqui começa a parte prática rumo aos seus novos contatos profissionais. Siga os passos abaixo:</p>
    <ol>
        <li>Preencha o cadastro abaixo</li>
        <li>Faça o pagamento da taxa de cadastro</li>
        <li>Mantenha-se disponível para receber os contatos de nossos parceiros.</li>
    </ol>

    <div class="home-page-posts animated fadeIn">

        <h4>Ficha de cadastro</h4>

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                <label for="Nome">Nome</label>
                <input type="text" placeholder="João" class="form-control" name="Nome" id="Nome">
            </div>
                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Sobrenome">Sobrenome</label>
                    <input type="text" placeholder="dos Santos Oliveira" class="form-control" name="Sobrenome" id="Sobrenome">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Email">E-mail</label>
                    <input type="email" placeholder="email@email.com" class="form-control" name="Email" id="Email">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Telefone">Telefone</label>
                    <input type="text" placeholder="(31)9999-9999" class="form-control" name="Telefone" id="Telefone">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Idade">Idade</label>
                    <input type="number" placeholder="18" class="form-control" name="Idade" id="Idade" style="text-align:center">
                </div>
                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Sexo">Sexo</label>
                    <select id="Sexo" name="Sexo" class="form-control">
                        <option value="1">Masculino</option>
                        <option value="2">Feminino</option>
                    </select>
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Logradouro">Logradouro</label>
                    <input type="text" placeholder="Rua..." class="form-control" name="Logradouro" id="Logradouro">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Bairro">Bairro</label>
                    <input type="text" placeholder="Santo Antônio" class="form-control" name="Bairro" id="Bairro">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Cidade">Cidade</label>
                    <input type="text" placeholder="Belo Horizonte" class="form-control" name="Cidade" id="Cidade">
                </div>

                <div class="form-group col-sm-6 correcaoalinhamentoinputsformcadastro">
                    <label for="Estado">Estado</label>
                    <input type="text" placeholder="MG" class="form-control" name="Estado" id="Estado" maxlength="2">
                </div>

                <div class="form-group">
                    <label for="PossuiExperiencia" style="padding-right:5px">Você possui experiência?</label>
                    @Html.CheckBoxFor(model => model.PossuiExperiencia, new { id = "PossuiExperiencia" })
                </div>

                <div class="form-group">

                    <label for="TipoExperiencia">Caso sim, em qual atuação?</label><br>

                    <label for="ExperienciaGarcom" style="padding-right:5px">Garçom</label>
                    @Html.CheckBoxFor(model => model.ExperienciaCopeiro, new { id = "ExperienciaGarcom" })
                    <br />
                    <label for="ExperienciaBarman" style="padding-right:5px">Barman</label>
                    @Html.CheckBoxFor(model => model.ExperienciaGarcom, new { id = "ExperienciaBarman" })
                    <br />
                    <label for="ExperienciaSeguranca" style="padding-right:5px">Segurança</label>
                    @Html.CheckBoxFor(model => model.ExperienciaSeguranca, new { id = "ExperienciaSeguranca" })
                    <br />
                    <label for="ExperienciaDj" style="padding-right:5px">DJ</label>
                    @Html.CheckBoxFor(model => model.ExperienciaDj, new { id = "ExperienciaDj" })
                    <br />
                    <label for="ExperienciaCopeiro" style="padding-right:5px">Copeiro</label>
                    @Html.CheckBoxFor(model => model.ExperienciaCopeiro, new { id = "ExperienciaCopeiro" })
                    <br />
                    <label for="ExperienciaFritadeira" style="padding-right:5px">Fritadeira</label>
                    @Html.CheckBoxFor(model => model.ExperienciaFritadeira, new { id = "ExperienciaFritadeira" })
                    <br />
                    <label for="ExperienciaHostness" style="padding-right:5px">Hostness (Recepção de eventos)</label>
                    @Html.CheckBoxFor(model => model.ExperienciaHostness, new { id = "ExperienciaHostness" })
                    <br />
                    <label for="ExperienciaMusico" style="padding-right:5px">Músico</label>
                    @Html.CheckBoxFor(model => model.ExperienciaMusico, new { id = "ExperienciaMusico" })
                    <br />
                    <label for="ExperienciaCaixa" style="padding-right:5px">Caixa</label>
                    @Html.CheckBoxFor(model => model.ExperienciaCaixa, new { id = "ExperienciaCaixa" })
                    <br />
                    <label for="ExperienciaPromotorEventos" style="padding-right:5px">Eventos</label>
                    @Html.CheckBoxFor(model => model.ExperienciaPromotorEventos, new { id = "ExperienciaPromotorEventos" })
                    <br />
                    <label for="ExperienciaAnimadorFestas" style="padding-right:5px">Animador de Festas</label>
                    @Html.CheckBoxFor(model => model.ExperienciaAnimadorFestas, new { id = "ExperienciaAnimadorFestas" })
                    <br />
                    <label for="ExperienciaManobrista" style="padding-right:5px">Manobrista</label>
                    @Html.CheckBoxFor(model => model.ExperienciaManobrista, new { id = "ExperienciaManobrista" })
                    <br />
                    <label for="ExperienciaSevicosGerais" style="padding-right:5px">Serviços Gerais</label>
                    @Html.CheckBoxFor(model => model.ExperienciaSevicosGerais, new { id = "ExperienciaSevicosGerais" })
                    <br />
                    <label for="ExperienciaFotografo" style="padding-right:5px">Fotografo</label>
                    @Html.CheckBoxFor(model => model.ExperienciaFotografo, new { id = "ExperienciaFotografo" })
                    <br />

                    @*<label for="TipoExperiencia">Caso sim, em qual atuação?</label><br>
                        <input type="checkbox" name="vehicle" value="garcom"> Garçom<br>
                        <input type="checkbox" name="vehicle" value="barman"> Barman<br>
                        <input type="checkbox" name="vehicle" value="seguranca"> Segurança<br>
                        <input type="checkbox" name="vehicle" value="dj"> DJ<br>
                        <input type="checkbox" name="vehicle" value="copeiro"> Copeiro<br>
                        <input type="checkbox" name="vehicle" value="fritadeira"> Fritadeira <br>
                        <input type="checkbox" name="vehicle" value="hostess"> Hostess (Recepção de eventos)<br>
                        <input type="checkbox" name="vehicle" value="musico"> Músico <br>
                        <input type="checkbox" name="vehicle" value="caixa"> Caixa <br>
                        <input type="checkbox" name="vehicle" value="promotor_eventos"> Promotor de evento <br>
                        <input type="checkbox" name="vehicle" value="animador_festas"> Animador de festas infantis <br>
                        <input type="checkbox" name="vehicle" value="manobrista"> Manobrista <br>
                        <input type="checkbox" name="vehicle" value="servicos_gerais"> Serviços Gerais <br>
                        <input type="checkbox" name="vehicle" value="fotografo"> Fotógrafo <br>*@
                </div>

                <div class="form-group">
                    <label for="LocalExperiencia">Pode nos contar um pouco sobre sua experiência?</label>
                    <textarea class="form-control" name="LocalExperiencia" id="LocalExperiencia" placeholder="Já trabalhei como freelancer nos eventos..."></textarea>
                </div>

                <div class="form-group">
                    <input class="btn btn-laranja btn-lg" type="submit" value="Cadastre-se">
                </div>
        }
        @*<div>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="BWRC6L2WE9LQC">
                    <input type="image" src="https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - A maneira fácil e segura de enviar pagamentos online!">
                    <img alt="" border="0" src="https://www.paypalobjects.com/pt_BR/i/scr/pixel.gif" width="1" height="1">
                </form>
            </div>*@
    </div>


</section><!-- main content -->

@Scripts.Render("~/Content/js/vendor/jquery-1.11.2.min.js")
@Scripts.Render("~/Content/materialize/js/materialize.min.js")

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-96040922-1', 'auto');
    ga('send', 'pageview');

</script>

@*@Styles.Render("~/Content/materialize/css/materialize.min2.css")*@

BlogMundoDesignMVC/Views/Profissionals/FinalizarFree.cshtml
@{
    ViewBag.Title = "Finalizar";
}

<section class="col-md-8 col-sm-6 col-md-offset-6 main-content"> 
    <h3>Cadastro confirmado!</h3>
    
    <p>Fique de olho nas nossas oportunidades!</p>

</section>


<script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-96040922-1', 'auto');
        ga('send', 'pageview');

</script>