BlogMundoDesignMVC/Models/Postagem.cs
namespace BlogMundoDesignMVC.Models
{
    public class Postagem
    {
        public string IdPostagem { get; set; }
        public string ConteudoPrimeiroNivelPostagem { get; set; }
        public string ConteudoSegundoNivelPostagem { get; set; }
        public string DataPostagem { get; set; }
        public string ImagemPostBase64 { get; set; }
        public string NomeAutor { get; set; }
        public string SubtituloPostagem { get; set; }
        public string TituloMeioPostagem { get; set; }
        public string TituloPostagem { get; set; }
        public string FotoAutor { get; set; }


    }
}

BlogMundoDesignMVC/Controllers/PostagemController.cs
using BlogMundoDesignMVC.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace BlogMundoDesignMVC.Controllers
{
    public class PostagemController : Controller
    {
       

        // GET: Postagem
        public ActionResult Index()
        {
            var wc = new WebClient();
            var json = wc.DownloadString("https://blogmundodesign.firebaseio.com/postagens.json");
            var lista = JsonConvert.DeserializeObject<IDictionary<string, Postagem>>(json);

            ViewBag.ListaPostagem = lista;

            return View();
        }

        // GET: Postagem/Details/5
        public ActionResult Details(string idPostagem)
        {

            var wc = new WebClient();
            var json = wc.DownloadString("https://blogmundodesign.firebaseio.com/postagens.json");
            var lista = JsonConvert.DeserializeObject<IDictionary<string, Postagem>>(json);

            var postagem = new Postagem();

            foreach (var item in lista)
            {
                if (item.Key == idPostagem)
                {


                    postagem.ConteudoPrimeiroNivelPostagem = item.Value.ConteudoPrimeiroNivelPostagem;
                    postagem.ConteudoSegundoNivelPostagem = item.Value.ConteudoSegundoNivelPostagem;
                    postagem.DataPostagem = item.Value.DataPostagem;
                    postagem.NomeAutor = item.Value.NomeAutor;
                    postagem.SubtituloPostagem = item.Value.SubtituloPostagem;
                    postagem.TituloMeioPostagem = item.Value.TituloMeioPostagem;
                    postagem.TituloPostagem = item.Value.TituloPostagem;
                    postagem.ImagemPostBase64 = item.Value.ImagemPostBase64;
                    postagem.FotoAutor = item.Value.FotoAutor;

                }
            }


            return View(postagem);
        }

        public ActionResult NovaPostagem()
        {
            return View();
        }

        // GET: Postagem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Postagem/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Postagem/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Postagem/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Postagem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Postagem/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

BlogMundoDesignMVC/Views/Postagem/About.cshtml
@using System.Runtime.InteropServices

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Sobre Nós - Vou de Freela</title>
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/Content/css/main.css" rel="stylesheet" />
</head>
<body>
    <main class="container left-container">
        <div class="row">
            <div id="menu-target">
                <ul>
                    <li><i class="fa fa-home"></i><a href="@Url.Action("About", "Postagem")">Home</a></li>
                    <li><i class="fa fa-anchor"></i><a href="@Url.Action("Create", "Profissionals")">Faça Parte</a></li>
                    <li><i class="fa fa-paper-plane"></i><a href="@Url.Action("Contato", "Profissionals")">Fale Conosco</a></li>
                </ul>
                <hr>

            </div>
            <section class="sidebar col-md-4 col-sm-12" style="background-image:url(/Content/img/home_default.jpg)">
                <span class="menu-trigger animated fadeInDown">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </span>

                <!--<div class="site-info">
                    <div class="primary-info">
                        <h1>Vou de Freela</h1>
                        <p>Aqui uma mensagem bonitinha</p>
                        <p>Aqui outra mensagem bonitinha</p>
                    </div>
                    <div class="secondary-info">
                        <p>
                            <a class="btn btn-primary" href="@Url.Action("Create", "Profissionals")"><i class="fa fa-user-plus"></i>Faça parte!</a>
                        </p>
                    </div>
                </div>-->
            </section><!-- end sidebar -->

        </div>
        <section class="col-md-8 col-sm-6 col-md-offset-6 main-content">
            <div class="sub-nav">
                <h2>Sobre nós</h2>
                <p>A Vou de Freela é uma empresa que surgiu com uma missão: aproximar quem precisa trabalhar como freelancer e quem precisa de freelas.</p>
                <p>Observando os amigos, conhecidos e o mercado da região metropolitana de Belo Horizonte percebemos o quão difícil pode ser para uma pessoa que não tem contatos mas precisa de “grana”, encontrar uma forma entrar no mercado de freelancers para eventos. </p>
                <p>Resolvemos então, indagar empreendedores do setor percebemos que também há a dificuldade da parte deles em saber quem está disponível e deseja esse tipo de trabalho; por isso eles sempre se restringem aos mesmos profissionais e/ ou indicações.</p>
                <p>Enfim, não foi difícil ter a ideia de juntar as duas pontas e por isso estamos aqui com o propósito de dar visibilidade à quem precisa do emprego e levar à quem precisa contratar mais opções com qualidade. Ou seja, juntar a fome com a vontade de comer!</p>
                <p>Então se você faz parte dessa turma que anseia por trabalho, ou se você dá oportunidades para essa galera disposta a ganhar uma grana com suor do seu trabalho; se cadastre aí ou entre em contato com a gente!</p>
            </div>
            
            <div class="secondary-info">
                <p>
                    <a class="btn btn-primary" href="@Url.Action("Create", "Profissionals")"><i class="fa fa-user-plus"></i> Faça parte!</a>
                </p>
            </div>
        </section>
    </main>


    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@

    @*<script src="../../../../../ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>*@
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
    <script src="~/Content/js/vendor/jquery.jpanelmenu.min.js"></script>
    <script src="~/Content/js/vendor/bootstrap.min.js"></script>
    <script src="~/Content/js/vendor/fastclick.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-96040922-1', 'auto');
        ga('send', 'pageview');

    </script>

</body>
</html>

BlogMundoDesignMVC/Views/Postagem/Create.cshtml
@model BlogMundoDesignMVC.Models.Postagem







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogMundoDesignMVC/Views/Postagem/Details.cshtml
@model BlogMundoDesignMVC.Models.Postagem

@{
    Layout = null;
}

<header class="hero-image" role="banner" style="background-image: url(/Content/img/default-single-hero-with-sidebar.jpg);">
    <span class="menu-trigger animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </span>
    <div id="menu-target">
        <ul>
            <li><i class="fa fa-home"></i>@Html.ActionLink("Home", "Index")</li>
            <li><i class="fa fa-anchor"></i><a href="page.html">About</a></li>
            <li><i class="fa fa-paper-plane"></i><a href="contact.html">Contact</a></li>
        </ul>
        <hr>
    </div>
</header>


<main class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8 single-content-sidebar">

            <h1>@Model.TituloPostagem</h1>
            <p class="subtitle">@Model.SubtituloPostagem</p>
            <p>@Model.ConteudoPrimeiroNivelPostagem</p>
            <p class="pullquote">@Model.TituloMeioPostagem</p>

            <p>@Model.ConteudoSegundoNivelPostagem</p>

        </div><!-- main-content/col -->
        @* Conteúdo lateral direito da postagem *@
        <div class="col-xs-12 col-md-3 col-md-offset-1 single-content-sidebar-area">
            <img src="~/Content/img/profile-1.jpg" class="user-icon " alt="user-image">
            <div class="meta">
                <div class="sidebar-info">
                    <a href="#">@Model.NomeAutor</a>
                </div>
                <div class="sidebar-readtime">
                    <i class="fa fa-bookmark"></i> @Model.DataPostagem
                </div>
            </div>
            
            <h2 class="favorites">Fique por dentro</h2>
            <a href="category.html">
                <div class="similar-cat">
                    <img src="~/Content/img/similar-cat-1.jpg">
                    <h3>Titulo Chamativo</h3>
                </div>
            </a>

        </div>
        @* Fim do conteúdo latera da postagem *@
        
        

    </div>
</main>
<footer class="single without-readmore">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-2">
                <img src="~/Content/img/profile-1.jpg" class="user-icon " alt="user-image">
            </div>
            <div class="col-xs-12 col-sm-6">
                <div class="category-list">
                    <p>Publicado em <span>@Model.DataPostagem</span></p>
                    <p><a href="#">@Model.NomeAutor</a>
                    <div class="other-catergories">
                        @*<h3>Also found in</h3>
                        <ul>
                            <li><a href="#">Stories</a>,</li>
                            <li><a href="#">Life</a>,</li>
                            <li><a href="#">Adventures</a></li>
                        </ul>*@
                    </div>
                </div>
            </div><!-- end col -->
            <div class="col-xs-12 col-sm-4">
                <div class="social">
                    <p>
                        Compartilhe este Blog Post
                        <div class="social-links">
                            <a class="social-icon" href="#" data-platform="twitter" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-twitter"></i></a>
                            <a class="social-icon" href="#" data-platform="facebook" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-facebook-official"></i></a>
                            <a class="social-icon" data-platform="mail" href="mailto:support@writertheme.com"><i class="fa fa-envelope"></i></a>
                        </div>
                </div>
            </div>
        </div><!-- end row -->
    </div>
</footer>


@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")

@Scripts.Render("~/bundles/jquery")
@*@Scripts.Render("~/bundles/bootstrap")*@

@*<script src="../../../../../ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>*@
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
<script src="~/Content/js/vendor/jquery.jpanelmenu.min.js"></script>
<script src="~/Content/js/vendor/bootstrap.min.js"></script>
<script src="~/Content/js/vendor/fastclick.min.js"></script>
<script src="~/Content/js/main.js"></script>

BlogMundoDesignMVC/Views/Postagem/Index.cshtml
<section class="col-md-8 col-sm-6 col-md-offset-6 main-content">
    <div class="sub-nav">
        <a href="#" class="select-posts active">Faça parte</a>
    </div>
    
    

 
</section><!-- main content -->

BlogMundoDesignMVC/Views/Postagem/NovaPostagem.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="no-js">

<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Novo Post</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
</head>
<body>
    <!-- if the user has javascript disabled they can still use the menu -->
    
    <!-- end no script -->
    <main class="container left-container">
        <div class="row">
           
            <div class="col-md-12 col-sm-12 col-md-offset-0 main-content">
                <h3>Novo Post</h3>
                <form>
                    <div class="form-group">
                        <label for="NomeAutor">Nome do Autor</label>
                        <input type="text" placeholder="" class="form-control" id="NomeAutor">
                    </div>
                    <div class="form-group">
                        <label for="DataPostagem">Data da Postagem</label>
                        <input type="text" placeholder="16/03/2017" class="form-control" id="DataPostagem">
                    </div>
                    <div class="form-group">
                        <label for="TituloPostagem">Título do Post</label>
                        <input type="text" placeholder="" class="form-control" id="TituloPostagem">
                    </div>
                    <div class="form-group">
                        <label for="SubtituloPostagem">Subtítulo da Postagem</label>
                        <input type="text" placeholder="" class="form-control" id="SubtituloPostagem">
                    </div>
                    <div class="form-group">
                        <label for="ConteudoPrimeiroNivelPostagem">Conteúdo Primeiro Nível</label>
                        <textarea class="form-control" ID="ConteudoPrimeiroNivelPostagem"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="TituloMeioPostagem">Título Meio do Post</label>
                        <input type="text" placeholder="" class="form-control" id="TituloMeioPostagem">
                    </div>
                    <div class="form-group">
                        <label for="ConteudoSegundoNivelPostagem">Conteúdo Segundo Nível da Postagem</label>
                        <textarea class="form-control" ID="ConteudoSegundoNivelPostagem"></textarea>
                    </div>
                    <div class="form-group">
                    <input class="btn btn-default" type="submit" id="btnNovaPostagem" value="VAI FILHÃO">
                </div>
            </form>
        
        </div><!-- main content -->
    </div> <!--/row -->
</main> <!-- /container -->
    
    
</body>
</html>


@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/Scripts/FormularioPostagem/FormNovaPostagem.js")